<?php

$elders = array(
    " ",
    "Antonio Josue II",
    "Carlos Hernandez",
    "Constancio Mendoza Jr.",
    "Fernando Bagas Jr.",
    "Jed Gutierrez",
    "Jun Dizon",
    "Limuel Torres",
    "Rey Abrenica",
    "Sal Bongato"
);

$publishers = array(
    " ",
    "--ELDERS--", 
    "Antonio Josue II",
    "Carlos Hernandez",
    "Constancio Mendoza Jr.",
    "Fernando Bagas Jr.",
    "Jed Gutierrez",
    "Jun Dizon",
    "Limuel Torres",
    "Rey Abrenica",
    "Sal Bongato",
    " ", 
    "--SERVANTS--",
    "Jeremy Villavicente",
    "Joseph Villavicente",
    "Marte Bustamante",
    "Mario Sebastian",
    "Noli Sampang",
    "Ric Abueg",
    "Rosario Talvo",
    " ", 
    "--BROTHERS--", 
    "Benjamin Abrenica",
    "Daniel Yabut",
    "Joey Villavicente",
    "Ivan Soto",
    "Norman Gavino",
    "Raymond Hernandez",
    "Robin Obidos",
    "Timothy Abrenica",
    " ", 
    "--SISTERS--", 
    "Aizle Vargas",
    "Amelia Torres",
    "Annie Abrenica",
    "Celestina Tarranco",
    "Charm Gutierrez",
    "Cresencia Dizon",
    "Cynthia Josue",
    "Divinia Caparros",
    "Esther Monzon",
    "Eunice Cabuco",
    "Elisa Talvo",
    "Gloria Fernandez",
    "Godafreda Lucero",
    "Guiliana Landicho",
    "Ivy Landicho",
    "Josephine Abueg",
    "Josephine Galindo",
    "Julie Villavicente",
    "Kathleen Clair Abrenica",
    "Lourdes Dizon",
    "Lyrere Ann Obidos",
    "Marieta Domingo",
    "Marylou Dizon",
    "Melchora Gavino",
    "Miles Abrenica",
    "Mila Piefer",
    "Noemi Sampang",
    "Nora Hernandez",
    "Nelly Villavicente",
    "Rosalinda Sabordo",
    "Rosalynn Bernardo",
    "Ruth Rebong",
    "Sony Bagas",
    "Teresita Bustamante",
    "Zhayuri Sampang"
);

